name: Test Ruby Client 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
       platform: [ ubuntu-latest, macos-latest ]
       # platform: [ ubuntu-latest, macos-latest, windows-latest ]
       # platform: [ windows-latest ]
       ruby-version: ['2.6', '2.7']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: actions/checkout@v2
      # - name: Add GITHUB_WORKSPACE to the path
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     echo "::add-path::${env:GITHUB_WORKSPACE}"
      #     echo "Added GITHUB_WORKSPACE to path"
      # - uses: crazy-max/ghaction-chocolatey@v1
      #   with:
      #     args: install curl -y
      #   if: matrix.platform == 'windows-latest'
      # - name: Testing on ${{ matrix.platform }} for Ruby ${{ matrix.ruby }}
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     # echo "need to fix path to libcurl.dll"
      #     cd src/ruby_client
      #     bundle install
      #     bundle info emass_client
      #     rspec -I src/ruby_client/lib -I src/ruby_client/spec .\src\ruby_client\spec --format progress
      - name: Testing on ${{ matrix.platform }} for Ruby ${{ matrix.ruby }}
        if: matrix.platform == 'ubuntu-latest'
        env: 
          CI_LIB_PATH: /home/runner/work/emass_client/emass_client/src/ruby_client/lib
          CI_SPEC_PATH: /home/runner/work/emass_client/emass_client/src/ruby_client/spec
        run: |
          cd src/ruby_client
          bundle install
          bundle info emass_client
          rspec -I "${{ env.CI_LIB_PATH }}" -I "${{ env.CI_SPEC_PATH }}" "${{ env.CI_SPEC_PATH }}" --format progress
      - name: Testing on ${{ matrix.platform }} for Ruby ${{ matrix.ruby }}
        if: matrix.platform == 'macos-latest'
        env: 
          CI_LIB_PATH: /Users/runner/work/emass_client/emass_client/src/ruby_client/lib
          CI_SPEC_PATH: /Users/runner/work/emass_client/emass_client/src/ruby_client/spec
        run: |
          echo "pwd is"
          pwd
          echo "LIB_PATH IS:"
          pwd/src/ruby_client/lib
          cd src/ruby_client
          bundle install
          bundle info emass_client
          rspec -I "${{ env.CI_LIB_PATH }}" -I "${{ env.CI_SPEC_PATH }}" "${{ env.CI_SPEC_PATH }}" --format progress
        